<a href="https://colab.research.google.com/github/singhsourav0/DeepLearningOdyssey/blob/main/Backpropagation_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.DataFrame([[8,7,4],[8,4,6],[9, 7,4],[6,10,6]], columns =['cgpa','score','lpa'])
df

cgpa  score  lpa
0     8      7    4
1     8      4    6
2     9      7    4
3     6     10    6

In [21]:
#create initilize parameters
def initialize_parameters(layers_dim):

  np.random.seed(3)
  parameters ={}
  L = len(layers_dim)

  for l in  range(1,L):
     parameters['W' + str(l)] = np.ones((layers_dim[l-1], layers_dim[l]))*0.1
     parameters['b' + str(l)] = np.zeros((layers_dim[l], 1))

  return parameters

In [22]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [23]:
def linear_forward(A_prev, w,b):
  z = np.dot(w.T, A_prev)+b
  return z

In [24]:
#main forward propagation
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [25]:
X = df[['cgpa', 'score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [26]:
y_hat = y_hat[0][0]

In [27]:
A1

array([[1.5],
       [1.5]])

In [29]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [30]:
update_parameters(parameters,y,y_hat,A1,X)

In [31]:
parameters

{'W1': array([[0.10657712, 0.10575498],
        [0.10657712, 0.10575498]]),
 'b1': array([[0.00082214],
        [0.00082214]]),
 'W2': array([[0.1111],
        [0.1111]]),
 'b2': array([[0.1185]])}

In [35]:
X = df[['cgpa', 'score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

In [37]:
X = df[['cgpa', 'score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10657712, 0.10575498],
        [0.10657712, 0.10575498]]),
 'b1': array([[0.00082214],
        [0.00082214]]),
 'W2': array([[0.1111],
        [0.1111]]),
 'b2': array([[0.1185]])}

In [38]:
X = df[['cgpa', 'score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11781199, 0.11137241],
        [0.11780209, 0.11136747]]),
 'b1': array([[0.0022265 ],
        [0.00222526]]),
 'W2': array([[0.12542866],
        [0.1253182 ]]),
 'b2': array([[0.13651467]])}

In [40]:
X = df[['cgpa', 'score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12628227, 0.11796041],
        [0.12622267, 0.1179168 ]]),
 'b1': array([[0.00316764],
        [0.00316088]]),
 'W2': array([[0.13827334],
        [0.13746182]]),
 'b2': array([[0.14426821]])}

In [42]:
X = df[['cgpa', 'score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.13647552, 0.13494916],
        [0.13627394, 0.13466892]]),
 'b1': array([[0.00486652],
        [0.00483609]]),
 'W2': array([[0.15978352],
        [0.15755794]]),
 'b2': array([[0.16819029]])}

In [49]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  21.218433661372927
Epoch -  2 Loss -  16.95255036028114
Epoch -  3 Loss -  11.54038350550595
Epoch -  4 Loss -  6.431888438814288
Epoch -  5 Loss -  3.397934893944273


{'W1': array([[0.31761759, 0.3011519 ],
        [0.31241576, 0.29610706]]),
 'b1': array([[0.02921005],
        [0.02849786]]),
 'W2': array([[0.41784733],
        [0.40207219]]),
 'b2': array([[0.40588761]])}

Now we will also update weights and bias from backpropagation by using keras.

In [52]:
df

cgpa  score  lpa
0     8      7    4
1     8      4    6
2     9      7    4
3     6     10    6

In [53]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


In [76]:
model = Sequential()

model.add(Dense(2, activation= 'linear',input_dim =2))
model.add(Dense(1,activation = 'linear'))

model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [77]:
model.get_weights()

[array([[ 1.0049268, -0.3223561],
        [-0.5392327,  0.7466271]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.2031333],
        [-0.6488251]], dtype=float32),
 array([0.], dtype=float32)]

In [78]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype = np.float32),
               np.array([.0,.0] ,dtype = np.float32),
               np.array([[0.1],[0.1]],dtype = np.float32),
               np.array([.0],dtype = np.float32)]

In [79]:
model.set_weights(new_weights)

In [80]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [81]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [82]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs =75,verbose = 1, batch_size = 1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 23.0588
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 22.8022
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 22.5180
Epoch 4/75
4/4 [==============================] - 0s 3ms/step - loss: 22.2554
Epoch 5/75
4/4 [==============================] - 0s 3ms/step - loss: 21.9532
Epoch 6/75
4/4 [==============================] - 0s 3ms/step - loss: 21.6547
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 21.3575
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 21.0422
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 20.7274
Epoch 10/75
4/4 [==============================] - 0s 2ms/step - loss: 20.3873
Epoch 11/75
4/4 [==============================] - 0s 3ms/step - loss: 20.0449
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 19.7120
Epoch 13/75
4/4 [==============================] - 0s 3ms/ste

In [84]:
model.get_weights()

[array([[0.37044755, 0.37044755],
        [0.35304195, 0.35304195]], dtype=float32),
 array([0.27127632, 0.27127632], dtype=float32),
 array([[0.3711136],
        [0.3711136]], dtype=float32),
 array([0.20475458], dtype=float32)]