<a href="https://colab.research.google.com/github/singhsourav0/Deep-Learning-Odyssey/blob/main/Bidirectional_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**Bidirectional LSTMs**

Bidirectional LSTMs are a type of recurrent neural network (RNN) architecture specifically designed for processing sequential data like text, time series, or audio signals. They address a limitation of standard LSTMs, which only process information in the forward direction (left to right). This can be insufficient for tasks where understanding the context from both sides of a sequence is crucial.

**How Bidirectional LSTMs Work**

Bidirectional LSTMs overcome this limitation by incorporating two LSTMs:

- <font color='green'>**Forward LSTM:**</font> Processes the sequence in the normal direction, capturing dependencies between earlier and later elements.
- <font color='green'>**Backward LSTM:**</font> Processes the sequence in the reverse direction, capturing dependencies between later and earlier elements.

This bidirectional processing allows Bidirectional LSTMs to leverage context from both sides of a sequence, leading to a more comprehensive understanding of the data.

**Advantages of Bidirectional LSTMs over LSTMs**

- <font color='green'>**Improved Contextual Understanding:**</font> Bidirectional LSTMs can better grasp the relationships between elements in a sequence by considering information from both directions. This is particularly beneficial for tasks like sentiment analysis (understanding the overall sentiment of a sentence) or machine translation (accurately capturing the meaning and context across languages).
- <font color='green'>**Modeling Long-Term Dependencies:**</font> Bidirectional LSTMs are adept at capturing long-range dependencies within sequences, which can be crucial for tasks where distant elements influence each other. For example, in speech recognition, the meaning of a word might depend on words spoken several seconds earlier.

**While it's true that all models, including AI models, have limitations and can be fooled by adversarial examples, Bidirectional LSTMs offer significant advantages over LSTMs in many sequential data processing tasks.**

**Implementation in Colab Notebooks (using Keras)**


**Key Points for Colab Implementation:**

- <font color='green'>**Import necessary libraries:**</font>
- <font color='green'>**Define hyperparameters:**</font>
- <font color='green'>**Data preprocessing:**</font>
- <font color='green'>**Model architecture:**</font> The `Bidirectional` layer is the core component. You can stack multiple Bidirectional LSTMs for more complex tasks.
- <font color='green'>**Compilation:**</font> Choose an appropriate loss function (e.g., 'categorical_crossentropy' for multi-class classification), optimizer (e.g., 'adam'), and metrics (e.g., 'accuracy').
- <font color='green'>**Training:**</font> Train the model on your data using the `fit` method.

Bidirectional LSTMs are a powerful tool for sequential data processing, but they are not a silver bullet. Carefully consider your specific task and data when choosing an appropriate model architecture.


In [ ]:
!pip install kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c fake-news


 97% 45.0M/46.5M [00:01<00:00, 42.9MB/s]
100% 46.5M/46.5M [00:01<00:00, 28.4MB/s]


In [ ]:
!unzip fake-news.zip

Archive:  fake-news.zip
  inflating: submit.csv              
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('train.csv')

In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
###Drop Nan Values
df=df.dropna()

In [ ]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [ ]:
## Get the Dependent features
y=df['label']

In [ ]:
y.value_counts()

label
0    10361
1     7924
Name: count, dtype: int64

In [ ]:
X.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf


In [ ]:
tf.__version__

'2.15.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [ ]:
### Vocabulary size
voc_size=5000

In [ ]:
messages=X.copy()

In [ ]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [ ]:
messages.reset_index(inplace=True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus]
onehot_repr

[[830, 3354, 4153, 4839, 2387, 2391, 1016, 2766, 4442, 3123],
 [1013, 571, 1952, 3365, 3483, 1117, 4994],
 [2207, 4603, 4703, 3492],
 [3836, 1597, 1688, 2754, 1211, 997],
 [2319, 3483, 1816, 1730, 162, 3533, 3483, 2880, 1725, 4366],
 [1752,
  2393,
  2175,
  4489,
  2485,
  4383,
  4204,
  3504,
  2260,
  1953,
  4842,
  4565,
  4286,
  2685,
  4994],
 [3362, 4287, 943, 569, 4035, 4981, 1149, 1833, 198, 1976, 3048],
 [169, 679, 3349, 167, 156, 4596, 4383, 2591, 198, 1976, 3048],
 [1910, 1471, 3129, 3193, 2173, 1003, 4701, 1076, 4383, 1699],
 [4722, 1282, 3573, 278, 2891, 3362, 4903, 3381],
 [1140, 2474, 3893, 165, 3230, 118, 1758, 249, 3704, 1878, 231],
 [2754, 2841, 2387, 1003, 4383, 156],
 [3549, 3456, 1426, 3577, 2651, 1404, 1997, 470, 2760],
 [3400, 1501, 337, 2380, 872, 4128, 4284, 198, 1976, 3048],
 [3006, 2095, 1661, 2532, 987, 198, 1976, 3048],
 [699, 3146, 4097, 2590, 3311, 2110, 4840, 956, 4961, 2351],
 [3616, 4763, 571],
 [3304, 3210, 1050, 1502, 4383, 4482, 4928, 4994],
 [2

In [ ]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2766 4442 3123]
 [   0    0    0 ... 3483 1117 4994]
 [   0    0    0 ... 4603 4703 3492]
 ...
 [   0    0    0 ...  198 1976 3048]
 [   0    0    0 ...  551 3187 3164]
 [   0    0    0 ... 2554  254 4788]]


In [ ]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,  830,
       3354, 4153, 4839, 2387, 2391, 1016, 2766, 4442, 3123], dtype=int32)

In [ ]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256501 (1001.96 KB)
Trainable params: 256501 (1001.96 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirection  (None, 200)               112800    
 al)                                                             
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313001 (1.19 MB)
Trainable params: 313001 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [ ]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [ ]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 27s 105ms/step - loss: 0.3095 - accuracy: 0.8546 - val_loss: 0.1986 - val_accuracy: 0.9153
Epoch 2/10
192/192 [==============================] - 18s 93ms/step - loss: 0.1361 - accuracy: 0.9482 - val_loss: 0.2027 - val_accuracy: 0.9188
Epoch 3/10
192/192 [==============================] - 24s 123ms/step - loss: 0.0909 - accuracy: 0.9669 - val_loss: 0.2363 - val_accuracy: 0.9188
Epoch 4/10
192/192 [==============================] - 16s 81ms/step - loss: 0.0583 - accuracy: 0.9793 - val_loss: 0.3019 - val_accuracy: 0.9183
Epoch 5/10
192/192 [==============================] - 16s 83ms/step - loss: 0.0399 - accuracy: 0.9855 - val_loss: 0.3267 - val_accuracy: 0.9085
Epoch 6/10
192/192 [==============================] - 16s 81ms/step - loss: 0.0245 - accuracy: 0.9918 - val_loss: 0.4112 - val_accuracy: 0.9152
Epoch 7/10
192/192 [==============================] - 16s 81ms/step - loss: 0.0204 - accuracy: 0.9931 - val_loss: 0.4739 - val_accurac

In [ ]:
y_pred1=model1.predict(X_test)

189/189 [==============================] - 4s 12ms/step


In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:

y_test = y_test.astype(np.int64)
y_pred1 = y_pred1.astype(np.int64)

# Recalculate the confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred1)

# Print the confusion matrix
print(confusion_matrix)

[[3419    0]
 [2616    0]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

In [ ]:

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))